# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{javagems}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["ggironda", "jaknowlden"]
  s.date = %q{2009-11-11}
  s.description = %q{Provides gem-esque support to Java}
  s.email = %q{gabriel.gironda@gmail.com}
  s.executables = ["javagem", "javagem"]
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     ".gitignore",
     "LICENSE",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "Rakefile",
     "VERSION",
     "bin/javagem",
     "jar/.gitignore",
     "jar/javagems.jar",
     "lib/javagems.rb"
  ]
  s.homepage = %q{http://www.javagems.org/}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{A gem for the javagems system}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

